export {default as Main} from './Main'
export {default as Projects} from './Projects'
export {default as Connect} from './Connect'
export {default as Navbar} from './Navbar'
export {default as Footbar} from './Footbar'